module.exports = {
  "bakta_v1.11.0": {
    "title": "bakta_v1.11.0 Parameters",
    "toolName": "bakta_v1.11.0",
    "route": "bakta_v1.11.0",
    "commandRoute": "/run-command-bakta_v1.11.0",
    "usagePath": "parameters/bakta_v1.11.0_usage.json",
    "paraPath": "parameters/bakta_v1.11.0_para.json",
    "html": "tool.ejs",
    "selectionRoute": "/complete-selection-bakta_v1.11.0",
    "env": "",
    "hasStderr": true
  },
  "bbduk_v37.62": {
    "title": "bbduk_v37.62 Parameters",
    "toolName": "bbduk_v37.62",
    "route": "bbduk_v37.62",
    "commandRoute": "/run-command-bbduk_v37.62",
    "usagePath": "parameters/bbduk_v37.62_usage.json",
    "paraPath": "parameters/bbduk_v37.62_para.json",
    "html": "tool.ejs",
    "selectionRoute": "/complete-selection-bbduk_v37.62",
    "env": "",
    "hasStderr": true
  },
  "bbmap_v37.62": {
    "title": "bbmap_v37.62 Parameters",
    "toolName": "bbmap_v37.62",
    "route": "bbmap_v37.62",
    "commandRoute": "/run-command-bbmap_v37.62",
    "usagePath": "parameters/bbmap_v37.62_usage.json",
    "paraPath": "parameters/bbmap_v37.62_para.json",
    "html": "tool.ejs",
    "selectionRoute": "/complete-selection-bbmap_v37.62",
    "env": "",
    "hasStderr": true
  },
  "cutadapt_v2.6": {
    "title": "cutadapt_v2.6 Parameters",
    "toolName": "cutadapt_v2.6",
    "route": "cutadapt_v2.6",
    "commandRoute": "/run-command-cutadapt_v2.6",
    "usagePath": "parameters/cutadapt_v2.6_usage.json",
    "paraPath": "parameters/cutadapt_v2.6_para.json",
    "html": "tool.ejs",
    "selectionRoute": "/complete-selection-cutadapt_v2.6",
    "env": "",
    "hasStderr": true
  },
  "dbcan_v4.1.4": {
    "title": "dbcan_v4.1.4 Parameters",
    "toolName": "dbcan_v4.1.4",
    "route": "dbcan_v4.1.4",
    "commandRoute": "/run-command-dbcan_v4.1.4",
    "usagePath": "parameters/dbcan_v4.1.4_usage.json",
    "paraPath": "parameters/dbcan_v4.1.4_para.json",
    "html": "tool.ejs",
    "selectionRoute": "/complete-selection-dbcan_v4.1.4",
    "env": "",
    "hasStderr": true
  },
  "gtdbtk_classify_wf_v2.4.0": {
    "title": "gtdbtk_classify_wf_v2.4.0 Parameters",
    "toolName": "gtdbtk_classify_wf_v2.4.0",
    "route": "gtdbtk_classify_wf_v2.4.0",
    "commandRoute": "/run-command-gtdbtk_classify_wf_v2.4.0",
    "usagePath": "parameters/gtdbtk_classify_wf_v2.4.0_usage.json",
    "paraPath": "parameters/gtdbtk_classify_wf_v2.4.0_para.json",
    "html": "tool.ejs",
    "selectionRoute": "/complete-selection-gtdbtk_classify_wf_v2.4.0",
    "env": "",
    "hasStderr": true
  },
  "metaphlan_v4.1.1": {
    "title": "metaphlan_v4.1.1 Parameters",
    "toolName": "metaphlan_v4.1.1",
    "route": "metaphlan_v4.1.1",
    "commandRoute": "/run-command-metaphlan_v4.1.1",
    "usagePath": "parameters/metaphlan_v4.1.1_usage.json",
    "paraPath": "parameters/metaphlan_v4.1.1_para.json",
    "html": "tool.ejs",
    "selectionRoute": "/complete-selection-metaphlan_v4.1.1",
    "env": "",
    "hasStderr": true
  },
  "metaspades_v4.2.0": {
    "title": "metaspades_v4.2.0 Parameters",
    "toolName": "metaspades_v4.2.0",
    "route": "metaspades_v4.2.0",
    "commandRoute": "/run-command-metaspades_v4.2.0",
    "usagePath": "parameters/metaspades_v4.2.0_usage.json",
    "paraPath": "parameters/metaspades_v4.2.0_para.json",
    "html": "tool.ejs",
    "selectionRoute": "/complete-selection-metaspades_v4.2.0",
    "env": "",
    "hasStderr": true
  },
  "pyani_v0.2.12": {
    "title": "pyani_v0.2.12 Parameters",
    "toolName": "pyani_v0.2.12",
    "route": "pyani_v0.2.12",
    "commandRoute": "/run-command-pyani_v0.2.12",
    "usagePath": "parameters/pyani_v0.2.12_usage.json",
    "paraPath": "parameters/pyani_v0.2.12_para.json",
    "html": "tool.ejs",
    "selectionRoute": "/complete-selection-pyani_v0.2.12",
    "env": "",
    "hasStderr": true
  },
  "fastqc_v0.12.1": {
    "title": "fastqc_v0.12.1 Parameters",
    "toolName": "fastqc_v0.12.1",
    "route": "fastqc_v0.12.1",
    "commandRoute": "/run-command-fastqc_v0.12.1",
    "usagePath": "parameters/fastqc_v0.12.1_usage.json",
    "paraPath": "parameters/fastqc_v0.12.1_para.json",
    "html": "tool.ejs",
    "selectionRoute": "/complete-selection-fastqc_v0.12.1",
    "env": "",
    "hasStderr": true
  },
  "blastall": {
    "title": "blastall Parameters",
    "toolName": "blastall",
    "route": "blastall",
    "commandRoute": "/run-command-blastall",
    "usagePath": "parameters/blastall_usage.json",
    "paraPath": "parameters/blastall_para.json",
    "html": "tool.ejs",
    "selectionRoute": "/complete-selection-blastall",
    "env": "",
    "hasStderr": true
  },
  "spades": {
    "title": "SPAdes Genome Assembler",
    "toolName": "spades",
    "route": "spades",
    "commandRoute": "/run-command-spades",
    "usagePath": "parameters/spades_usage.json",
    "paraPath": "parameters/spades_para.json",
    "html": "tool.ejs",
    "selectionRoute": "/complete-selection-spades",
    "env": "spades_env",
    "hasStderr": true,
    "conda_env": "spades_env"
  },
  "quast": {
    "title": "QUAST Assembly Quality Assessment",
    "toolName": "quast",
    "route": "quast",
    "commandRoute": "/run-command-quast",
    "usagePath": "parameters/quast_usage.json",
    "paraPath": "parameters/quast_para.json",
    "html": "tool.ejs",
    "selectionRoute": "/complete-selection-quast",
    "env": "quast_env",
    "hasStderr": true,
    "conda_env": "quast_env"
  },
  "StrainPhlAn_v4.0.6": {
    "title": "StrainPhlAn_v4.0.6 Parameters",
    "toolName": "StrainPhlAn_v4.0.6",
    "route": "StrainPhlAn_v4.0.6",
    "commandRoute": "/run-command-StrainPhlAn_v4.0.6",
    "usagePath": "parameters/StrainPhlAn_v4.0.6_usage.json",
    "paraPath": "parameters/StrainPhlAn_v4.0.6_para.json",
    "html": "tool.ejs",
    "selectionRoute": "/complete-selection-StrainPhlAn_v4.0.6",
    "env": "",
    "hasStderr": true
  },
  "trimmomatic_v0.40": {
    "title": "trimmomatic_v0.40 Parameters",
    "toolName": "trimmomatic_v0.40",
    "route": "trimmomatic_v0.40",
    "commandRoute": "/run-command-trimmomatic_v0.40",
    "usagePath": "parameters/trimmomatic_v0.40_usage.json",
    "paraPath": "parameters/trimmomatic_v0.40_para.json",
    "html": "tool.ejs",
    "selectionRoute": "/complete-selection-trimmomatic_v0.40",
    "env": "",
    "hasStderr": true
  },
  "kraken_v2.1.3": {
    "title": "kraken_v2.1.3 Parameters",
    "toolName": "kraken_v2.1.3",
    "route": "kraken_v2.1.3",
    "commandRoute": "/run-command-kraken_v2.1.3",
    "usagePath": "parameters/kraken_v2.1.3_usage.json",
    "paraPath": "parameters/kraken_v2.1.3_para.json",
    "html": "tool.ejs",
    "selectionRoute": "/complete-selection-kraken_v2.1.3",
    "env": "",
    "hasStderr": true
  },
  "humann_v3.9": {
    "title": "humann_v3.9 Parameters",
    "toolName": "humann_v3.9",
    "route": "humann_v3.9",
    "commandRoute": "/run-command-humann_v3.9",
    "usagePath": "parameters/humann_v3.9_usage.json",
    "paraPath": "parameters/humann_v3.9_para.json",
    "html": "tool.ejs",
    "selectionRoute": "/complete-selection-humann_v3.9",
    "env": "",
    "hasStderr": true
  },
  "megahit_v1.2.9": {
    "title": "megahit_v1.2.9 Parameters",
    "toolName": "megahit_v1.2.9",
    "route": "megahit_v1.2.9",
    "commandRoute": "/run-command-megahit_v1.2.9",
    "usagePath": "parameters/megahit_v1.2.9_usage.json",
    "paraPath": "parameters/megahit_v1.2.9_para.json",
    "html": "tool.ejs",
    "selectionRoute": "/complete-selection-megahit_v1.2.9",
    "env": "",
    "hasStderr": true
  },
  "metabat2_v2.12.1": {
    "title": "metabat2_v2.12.1 Parameters",
    "toolName": "metabat2_v2.12.1",
    "route": "metabat2_v2.12.1",
    "commandRoute": "/run-command-metabat2_v2.12.1",
    "usagePath": "parameters/metabat2_v2.12.1_usage.json",
    "paraPath": "parameters/metabat2_v2.12.1_para.json",
    "html": "tool.ejs",
    "selectionRoute": "/complete-selection-metabat2_v2.12.1",
    "env": "",
    "hasStderr": true
  },
  "prokka_v1.14.6": {
    "title": "prokka_v1.14.6 Parameters",
    "toolName": "prokka_v1.14.6",
    "route": "prokka_v1.14.6",
    "commandRoute": "/run-command-prokka_v1.14.6",
    "usagePath": "parameters/prokka_v1.14.6_usage.json",
    "paraPath": "parameters/prokka_v1.14.6_para.json",
    "html": "tool.ejs",
    "selectionRoute": "/complete-selection-prokka_v1.14.6",
    "env": "",
    "hasStderr": true
  },
  "phylophlan3": {
    "title": "phylophlan3 Parameters",
    "toolName": "phylophlan3",
    "route": "phylophlan3",
    "commandRoute": "/run-command-phylophlan3",
    "usagePath": "parameters/phylophlan3_usage.json",
    "paraPath": "parameters/phylophlan3_para.json",
    "html": "tool.ejs",
    "selectionRoute": "/complete-selection-phylophlan3",
    "env": "",
    "hasStderr": true
  },
  "roary": {
    "title": "roary Parameters",
    "toolName": "roary",
    "route": "roary",
    "commandRoute": "/run-command-roary",
    "usagePath": "parameters/roary_usage.json",
    "paraPath": "parameters/roary_para.json",
    "html": "tool.ejs",
    "selectionRoute": "/complete-selection-roary",
    "env": "",
    "hasStderr": true
  },
  "RAxML": {
    "title": "RAxML Parameters",
    "toolName": "RAxML",
    "route": "RAxML",
    "commandRoute": "/run-command-RAxML",
    "usagePath": "parameters/RAxML_usage.json",
    "paraPath": "parameters/RAxML_para.json",
    "html": "tool.ejs",
    "selectionRoute": "/complete-selection-RAxML",
    "env": "",
    "hasStderr": true
  },
  "IQ-Tree": {
    "title": "IQ-Tree Parameters",
    "toolName": "IQ-Tree",
    "route": "IQ-Tree",
    "commandRoute": "/run-command-IQ-Tree",
    "usagePath": "parameters/IQ-Tree_usage.json",
    "paraPath": "parameters/IQ-Tree_para.json",
    "html": "tool.ejs",
    "selectionRoute": "/complete-selection-IQ-Tree",
    "env": "",
    "hasStderr": true
  },
  "CheckV_end_to_end": {
    "title": "CheckV_end_to_end Parameters",
    "toolName": "CheckV_end_to_end",
    "route": "CheckV_end_to_end",
    "commandRoute": "/run-command-CheckV_end_to_end",
    "usagePath": "parameters/CheckV_end_to_end_usage.json",
    "paraPath": "parameters/CheckV_end_to_end_para.json",
    "html": "tool.ejs",
    "selectionRoute": "/complete-selection-CheckV_end_to_end",
    "env": "",
    "hasStderr": true
  },
  "VirSorter_Run": {
    "title": "VirSorter_Run Parameters",
    "toolName": "VirSorter_Run",
    "route": "VirSorter_Run",
    "commandRoute": "/run-command-VirSorter_Run",
    "usagePath": "parameters/VirSorter_Run_usage.json",
    "paraPath": "parameters/VirSorter_Run_para.json",
    "html": "tool.ejs",
    "selectionRoute": "/complete-selection-VirSorter_Run",
    "env": "",
    "hasStderr": true
  },
  "RGI_BWT": {
    "title": "RGI_BWT Parameters",
    "toolName": "RGI_BWT",
    "route": "RGI_BWT",
    "commandRoute": "/run-command-RGI_BWT",
    "usagePath": "parameters/RGI_BWT_usage.json",
    "paraPath": "parameters/RGI_BWT_para.json",
    "html": "tool.ejs",
    "selectionRoute": "/complete-selection-RGI_BWT",
    "env": "",
    "hasStderr": true
  }
};