module.exports = {
  "cutadapt": {
    "title": "Cutadapt Parameters",
    "toolName": "cutadapt",
    "route": "cutadapt",
    "commandRoute": "/run-command-cutadapt",
    "env": "source cutadapt-venv/bin/activate && __COMMAND__",
    "usagePath": "parameters/cutadapt_usage.json",
    "paraPath": "parameters/cutadapt_para.json",
    "html": "tool.ejs",
    "selectionRoute": "/complete-selection"
  },
  "metaphlan": {
    "title": "Metaphlan Parameters",
    "toolName": "metaphlan",
    "route": "metaphlan",
    "commandRoute": "/run-command-metaphlan",
    "env": "\n        bash -l -c \"\n          source ~/miniconda3/etc/profile.d/conda.sh;\n          conda activate mpa;\n          __COMMAND__\n        \"\n      ",
    "usagePath": "parameters/metaphlan_usage.json",
    "paraPath": "parameters/metaphlan_para.json",
    "html": "tool.ejs",
    "selectionRoute": "/complete-selection-metaphlan",
    "hasStderr": true
  },
  "BBtools": {
    "title": "BBtools Parameters",
    "toolName": "BBtools",
    "route": "BBtools",
    "commandRoute": "/run-command-BBtools",
    "env": "\n        \n      ",
    "usagePath": "parameters/BBtools_usage.json",
    "paraPath": "parameters/BBtools_para.json",
    "html": "tool.ejs",
    "selectionRoute": "/complete-selection-BBtools",
    "hasStderr": true
  },
  "bakta": {
    "title": "bakta Parameters",
    "toolName": "bakta",
    "route": "bakta",
    "commandRoute": "/run-command-bakta",
    "usagePath": "parameters/bakta_usage.json",
    "paraPath": "parameters/bakta_para.json",
    "html": "tool.ejs",
    "selectionRoute": "/complete-selection-bakta",
    "env": "",
    "hasStderr": true
  },
  "Cutadapt": {
    "title": "Cutadapt Parameters",
    "toolName": "Cutadapt",
    "route": "Cutadapt",
    "commandRoute": "/run-command-Cutadapt",
    "usagePath": "parameters/Cutadapt_usage.json",
    "paraPath": "parameters/Cutadapt_para.json",
    "html": "tool.ejs",
    "selectionRoute": "/complete-selection-Cutadapt",
    "env": "",
    "hasStderr": true
  },
  "Metaphlan": {
    "title": "Metaphlan Parameters",
    "toolName": "Metaphlan",
    "route": "Metaphlan",
    "commandRoute": "/run-command-Metaphlan",
    "usagePath": "parameters/Metaphlan_usage.json",
    "paraPath": "parameters/Metaphlan_para.json",
    "html": "tool.ejs",
    "selectionRoute": "/complete-selection-Metaphlan",
    "env": "",
    "hasStderr": true
  },
  "BBmap": {
    "title": "BBmap Parameters",
    "toolName": "BBmap",
    "route": "BBmap",
    "commandRoute": "/run-command-BBmap",
    "usagePath": "parameters/BBmap_usage.json",
    "paraPath": "parameters/BBmap_para.json",
    "html": "tool.ejs",
    "selectionRoute": "/complete-selection-BBmap",
    "env": "",
    "hasStderr": true
  },
  "PyANI": {
    "title": "PyANI Parameters",
    "toolName": "PyANI",
    "route": "PyANI",
    "commandRoute": "/run-command-PyANI",
    "usagePath": "parameters/PyANI_usage.json",
    "paraPath": "parameters/PyANI_para.json",
    "html": "tool.ejs",
    "selectionRoute": "/complete-selection-PyANI",
    "env": "",
    "hasStderr": true
  },
  "MetaSPADES": {
    "title": "MetaSPADES Parameters",
    "toolName": "MetaSPADES",
    "route": "MetaSPADES",
    "commandRoute": "/run-command-MetaSPADES",
    "usagePath": "parameters/MetaSPADES_usage.json",
    "paraPath": "parameters/MetaSPADES_para.json",
    "html": "tool.ejs",
    "selectionRoute": "/complete-selection-MetaSPADES",
    "env": "",
    "hasStderr": true
  },
  "Bowtie2": {
    "title": "Bowtie2 Parameters",
    "toolName": "Bowtie2",
    "route": "Bowtie2",
    "commandRoute": "/run-command-Bowtie2",
    "usagePath": "parameters/Bowtie2_usage.json",
    "paraPath": "parameters/Bowtie2_para.json",
    "html": "tool.ejs",
    "selectionRoute": "/complete-selection-Bowtie2",
    "env": "",
    "hasStderr": true
  },
  "Dbcan": {
    "title": "Dbcan Parameters",
    "toolName": "Dbcan",
    "route": "Dbcan",
    "commandRoute": "/run-command-Dbcan",
    "usagePath": "parameters/Dbcan_usage.json",
    "paraPath": "parameters/Dbcan_para.json",
    "html": "tool.ejs",
    "selectionRoute": "/complete-selection-Dbcan",
    "env": "",
    "hasStderr": true
  },
  "FastQC": {
    "title": "FastQC Parameters",
    "toolName": "FastQC",
    "route": "FastQC",
    "commandRoute": "/run-command-FastQC",
    "usagePath": "parameters/FastQC_usage.json",
    "paraPath": "parameters/FastQC_para.json",
    "html": "tool.ejs",
    "selectionRoute": "/complete-selection-FastQC",
    "env": "",
    "hasStderr": true
  },
  "GTDB_TK_Align": {
    "title": "GTDB_TK_Align Parameters",
    "toolName": "GTDB_TK_Align",
    "route": "GTDB_TK_Align",
    "commandRoute": "/run-command-GTDB_TK_Align",
    "usagePath": "parameters/GTDB_TK_Align_usage.json",
    "paraPath": "parameters/GTDB_TK_Align_para.json",
    "html": "tool.ejs",
    "selectionRoute": "/complete-selection-GTDB_TK_Align",
    "env": "",
    "hasStderr": true
  },
  "bokeh": {
    "title": "Bokeh Visualization",
    "toolName": "Bokeh",
    "route": "visualization/bokeh",
    "commandRoute": "/run-command-bokeh",
    "usagePath": "parameters/bokeh_usage.json",
    "paraPath": "parameters/bokeh_para.json",
    "html": "bokeh.ejs",
    "selectionRoute": "/complete-selection-bokeh",
    "env": "",
    "hasStderr": true,
    "icon": "ti-chart-dots"
  },
  "Gtdb Tk Classify": {
    "title": "Gtdb Tk Classify Parameters",
    "toolName": "Gtdb Tk Classify",
    "route": "Gtdb Tk Classify",
    "commandRoute": "/run-command-Gtdb Tk Classify",
    "usagePath": "parameters/Gtdb Tk Classify_usage.json",
    "paraPath": "parameters/Gtdb Tk Classify_para.json",
    "html": "tool.ejs",
    "selectionRoute": "/complete-selection-Gtdb Tk Classify",
    "env": "",
    "hasStderr": true
  },
  "gtdb_tk_classify_wf": {
    "title": "gtdb_tk_classify_wf Parameters",
    "toolName": "gtdb_tk_classify_wf",
    "route": "gtdb_tk_classify_wf",
    "commandRoute": "/run-command-gtdb_tk_classify_wf",
    "usagePath": "parameters/gtdb_tk_classify_wf_usage.json",
    "paraPath": "parameters/gtdb_tk_classify_wf_para.json",
    "html": "tool.ejs",
    "selectionRoute": "/complete-selection-gtdb_tk_classify_wf",
    "env": "",
    "hasStderr": true
  },
  "bakta_v1.11.0": {
    "title": "bakta_v1.11.0 Parameters",
    "toolName": "bakta_v1.11.0",
    "route": "bakta_v1.11.0",
    "commandRoute": "/run-command-bakta_v1.11.0",
    "usagePath": "parameters/bakta_v1.11.0_usage.json",
    "paraPath": "parameters/bakta_v1.11.0_para.json",
    "html": "tool.ejs",
    "selectionRoute": "/complete-selection-bakta_v1.11.0",
    "env": "",
    "hasStderr": true
  },
  "bbduk_v37.62": {
    "title": "bbduk_v37.62 Parameters",
    "toolName": "bbduk_v37.62",
    "route": "bbduk_v37.62",
    "commandRoute": "/run-command-bbduk_v37.62",
    "usagePath": "parameters/bbduk_v37.62_usage.json",
    "paraPath": "parameters/bbduk_v37.62_para.json",
    "html": "tool.ejs",
    "selectionRoute": "/complete-selection-bbduk_v37.62",
    "env": "",
    "hasStderr": true
  },
  "bbmap_v37.62": {
    "title": "bbmap_v37.62 Parameters",
    "toolName": "bbmap_v37.62",
    "route": "bbmap_v37.62",
    "commandRoute": "/run-command-bbmap_v37.62",
    "usagePath": "parameters/bbmap_v37.62_usage.json",
    "paraPath": "parameters/bbmap_v37.62_para.json",
    "html": "tool.ejs",
    "selectionRoute": "/complete-selection-bbmap_v37.62",
    "env": "",
    "hasStderr": true
  },
  "cutadapt_v2.6": {
    "title": "cutadapt_v2.6 Parameters",
    "toolName": "cutadapt_v2.6",
    "route": "cutadapt_v2.6",
    "commandRoute": "/run-command-cutadapt_v2.6",
    "usagePath": "parameters/cutadapt_v2.6_usage.json",
    "paraPath": "parameters/cutadapt_v2.6_para.json",
    "html": "tool.ejs",
    "selectionRoute": "/complete-selection-cutadapt_v2.6",
    "env": "",
    "hasStderr": true
  },
  "dbcan_v4.1.4": {
    "title": "dbcan_v4.1.4 Parameters",
    "toolName": "dbcan_v4.1.4",
    "route": "dbcan_v4.1.4",
    "commandRoute": "/run-command-dbcan_v4.1.4",
    "usagePath": "parameters/dbcan_v4.1.4_usage.json",
    "paraPath": "parameters/dbcan_v4.1.4_para.json",
    "html": "tool.ejs",
    "selectionRoute": "/complete-selection-dbcan_v4.1.4",
    "env": "",
    "hasStderr": true
  },
  "fastqc_v0.12.1": {
    "title": "fastqc_v0.12.1 Parameters",
    "toolName": "fastqc_v0.12.1",
    "route": "fastqc_v0.12.1",
    "commandRoute": "/run-command-fastqc_v0.12.1",
    "usagePath": "parameters/fastqc_v0.12.1_usage.json",
    "paraPath": "parameters/fastqc_v0.12.1_para.json",
    "html": "tool.ejs",
    "selectionRoute": "/complete-selection-fastqc_v0.12.1",
    "env": "",
    "hasStderr": true
  },
  "gtdb_tk_classify_wf_xiaoyu": {
    "title": "gtdb_tk_classify_wf_xiaoyu Parameters",
    "toolName": "gtdb_tk_classify_wf_xiaoyu",
    "route": "gtdb_tk_classify_wf_xiaoyu",
    "commandRoute": "/run-command-gtdb_tk_classify_wf_xiaoyu",
    "usagePath": "parameters/gtdb_tk_classify_wf_xiaoyu_usage.json",
    "paraPath": "parameters/gtdb_tk_classify_wf_xiaoyu_para.json",
    "html": "tool.ejs",
    "selectionRoute": "/complete-selection-gtdb_tk_classify_wf_xiaoyu",
    "env": "",
    "hasStderr": true
  },
  "gtdbtk_classify_wf_v2.4.0": {
    "title": "gtdbtk_classify_wf_v2.4.0 Parameters",
    "toolName": "gtdbtk_classify_wf_v2.4.0",
    "route": "gtdbtk_classify_wf_v2.4.0",
    "commandRoute": "/run-command-gtdbtk_classify_wf_v2.4.0",
    "usagePath": "parameters/gtdbtk_classify_wf_v2.4.0_usage.json",
    "paraPath": "parameters/gtdbtk_classify_wf_v2.4.0_para.json",
    "html": "tool.ejs",
    "selectionRoute": "/complete-selection-gtdbtk_classify_wf_v2.4.0",
    "env": "",
    "hasStderr": true
  },
  "metaphlan_v4.1.1": {
    "title": "metaphlan_v4.1.1 Parameters",
    "toolName": "metaphlan_v4.1.1",
    "route": "metaphlan_v4.1.1",
    "commandRoute": "/run-command-metaphlan_v4.1.1",
    "usagePath": "parameters/metaphlan_v4.1.1_usage.json",
    "paraPath": "parameters/metaphlan_v4.1.1_para.json",
    "html": "tool.ejs",
    "selectionRoute": "/complete-selection-metaphlan_v4.1.1",
    "env": "",
    "hasStderr": true
  },
  "metaspades_v4.2.0": {
    "title": "metaspades_v4.2.0 Parameters",
    "toolName": "metaspades_v4.2.0",
    "route": "metaspades_v4.2.0",
    "commandRoute": "/run-command-metaspades_v4.2.0",
    "usagePath": "parameters/metaspades_v4.2.0_usage.json",
    "paraPath": "parameters/metaspades_v4.2.0_para.json",
    "html": "tool.ejs",
    "selectionRoute": "/complete-selection-metaspades_v4.2.0",
    "env": "",
    "hasStderr": true
  },
  "pyani_v0.2.12": {
    "title": "pyani_v0.2.12 Parameters",
    "toolName": "pyani_v0.2.12",
    "route": "pyani_v0.2.12",
    "commandRoute": "/run-command-pyani_v0.2.12",
    "usagePath": "parameters/pyani_v0.2.12_usage.json",
    "paraPath": "parameters/pyani_v0.2.12_para.json",
    "html": "tool.ejs",
    "selectionRoute": "/complete-selection-pyani_v0.2.12",
    "env": "",
    "hasStderr": true
  },
  "net": {
    "title": "net Parameters",
    "toolName": "net",
    "route": "net",
    "commandRoute": "/run-command-net",
    "usagePath": "parameters/net_usage.json",
    "paraPath": "parameters/net_para.json",
    "html": "tool.ejs",
    "selectionRoute": "/complete-selection-net",
    "env": "",
    "hasStderr": true
  },
  "FastQC-1": {
    "title": "FastQC-1 Parameters",
    "toolName": "FastQC-1",
    "route": "FastQC-1",
    "commandRoute": "/run-command-FastQC-1",
    "usagePath": "parameters/FastQC-1_usage.json",
    "paraPath": "parameters/FastQC-1_para.json",
    "html": "tool.ejs",
    "selectionRoute": "/complete-selection-FastQC-1",
    "env": "",
    "hasStderr": true
  },
  "net-1": {
    "title": "net-1 Parameters",
    "toolName": "net-1",
    "route": "net-1",
    "commandRoute": "/run-command-net-1",
    "usagePath": "parameters/net-1_usage.json",
    "paraPath": "parameters/net-1_para.json",
    "html": "tool.ejs",
    "selectionRoute": "/complete-selection-net-1",
    "env": "",
    "hasStderr": true
  },
  "eula.1042": {
    "title": "eula.1042 Parameters",
    "toolName": "eula.1042",
    "route": "eula.1042",
    "commandRoute": "/run-command-eula.1042",
    "usagePath": "parameters/eula.1042_usage.json",
    "paraPath": "parameters/eula.1042_para.json",
    "html": "tool.ejs",
    "selectionRoute": "/complete-selection-eula.1042",
    "env": "",
    "hasStderr": true
  },
  "test_2": {
    "title": "test_2 Parameters",
    "toolName": "test_2",
    "route": "test_2",
    "commandRoute": "/run-command-test_2",
    "usagePath": "parameters/test_2_usage.json",
    "paraPath": "parameters/test_2_para.json",
    "html": "tool.ejs",
    "selectionRoute": "/complete-selection-test_2",
    "env": "",
    "hasStderr": true
  },
  "net_test": {
    "title": "net_test Parameters",
    "toolName": "net_test",
    "route": "net_test",
    "commandRoute": "/run-command-net_test",
    "usagePath": "parameters/net_test_usage.json",
    "paraPath": "parameters/net_test_para.json",
    "html": "tool.ejs",
    "selectionRoute": "/complete-selection-net_test",
    "env": "",
    "hasStderr": true
  },
  "dbcan_test": {
    "title": "dbcan_test Parameters",
    "toolName": "dbcan_test",
    "route": "dbcan_test",
    "commandRoute": "/run-command-dbcan_test",
    "usagePath": "parameters/dbcan_test_usage.json",
    "paraPath": "parameters/dbcan_test_para.json",
    "html": "tool.ejs",
    "selectionRoute": "/complete-selection-dbcan_test",
    "env": "",
    "hasStderr": true
  },
  "pyani_test": {
    "title": "pyani_test Parameters",
    "toolName": "pyani_test",
    "route": "pyani_test",
    "commandRoute": "/run-command-pyani_test",
    "usagePath": "parameters/pyani_test_usage.json",
    "paraPath": "parameters/pyani_test_para.json",
    "html": "tool.ejs",
    "selectionRoute": "/complete-selection-pyani_test",
    "env": "",
    "hasStderr": true
  }
};