module.exports = {
  "bakta_v1.11.0": {
    "title": "bakta_v1.11.0 Parameters",
    "toolName": "bakta_v1.11.0",
    "route": "bakta_v1.11.0",
    "commandRoute": "/run-command-bakta_v1.11.0",
    "usagePath": "parameters/bakta_v1.11.0_usage.json",
    "paraPath": "parameters/bakta_v1.11.0_para.json",
    "html": "tool.ejs",
    "selectionRoute": "/complete-selection-bakta_v1.11.0",
    "env": "",
    "hasStderr": true
  },
  "bbduk_v37.62": {
    "title": "bbduk_v37.62 Parameters",
    "toolName": "bbduk_v37.62",
    "route": "bbduk_v37.62",
    "commandRoute": "/run-command-bbduk_v37.62",
    "usagePath": "parameters/bbduk_v37.62_usage.json",
    "paraPath": "parameters/bbduk_v37.62_para.json",
    "html": "tool.ejs",
    "selectionRoute": "/complete-selection-bbduk_v37.62",
    "env": "",
    "hasStderr": true
  },
  "bbmap_v37.62": {
    "title": "bbmap_v37.62 Parameters",
    "toolName": "bbmap_v37.62",
    "route": "bbmap_v37.62",
    "commandRoute": "/run-command-bbmap_v37.62",
    "usagePath": "parameters/bbmap_v37.62_usage.json",
    "paraPath": "parameters/bbmap_v37.62_para.json",
    "html": "tool.ejs",
    "selectionRoute": "/complete-selection-bbmap_v37.62",
    "env": "",
    "hasStderr": true
  },
  "cutadapt_v2.6": {
    "title": "cutadapt_v2.6 Parameters",
    "toolName": "cutadapt_v2.6",
    "route": "cutadapt_v2.6",
    "commandRoute": "/run-command-cutadapt_v2.6",
    "usagePath": "parameters/cutadapt_v2.6_usage.json",
    "paraPath": "parameters/cutadapt_v2.6_para.json",
    "html": "tool.ejs",
    "selectionRoute": "/complete-selection-cutadapt_v2.6",
    "env": "",
    "hasStderr": true
  },
  "dbcan_v4.1.4": {
    "title": "dbcan_v4.1.4 Parameters",
    "toolName": "dbcan_v4.1.4",
    "route": "dbcan_v4.1.4",
    "commandRoute": "/run-command-dbcan_v4.1.4",
    "usagePath": "parameters/dbcan_v4.1.4_usage.json",
    "paraPath": "parameters/dbcan_v4.1.4_para.json",
    "html": "tool.ejs",
    "selectionRoute": "/complete-selection-dbcan_v4.1.4",
    "env": "",
    "hasStderr": true
  },
  "fastqc_v0.12.1": {
    "title": "fastqc_v0.12.1 Parameters",
    "toolName": "fastqc_v0.12.1",
    "route": "fastqc_v0.12.1",
    "commandRoute": "/run-command-fastqc_v0.12.1",
    "usagePath": "parameters/fastqc_v0.12.1_usage.json",
    "paraPath": "parameters/fastqc_v0.12.1_para.json",
    "html": "tool.ejs",
    "selectionRoute": "/complete-selection-fastqc_v0.12.1",
    "env": "",
    "hasStderr": true
  },
  "gtdbtk_classify_wf_v2.4.0": {
    "title": "gtdbtk_classify_wf_v2.4.0 Parameters",
    "toolName": "gtdbtk_classify_wf_v2.4.0",
    "route": "gtdbtk_classify_wf_v2.4.0",
    "commandRoute": "/run-command-gtdbtk_classify_wf_v2.4.0",
    "usagePath": "parameters/gtdbtk_classify_wf_v2.4.0_usage.json",
    "paraPath": "parameters/gtdbtk_classify_wf_v2.4.0_para.json",
    "html": "tool.ejs",
    "selectionRoute": "/complete-selection-gtdbtk_classify_wf_v2.4.0",
    "env": "",
    "hasStderr": true
  },
  "metaphlan_v4.1.1": {
    "title": "metaphlan_v4.1.1 Parameters",
    "toolName": "metaphlan_v4.1.1",
    "route": "metaphlan_v4.1.1",
    "commandRoute": "/run-command-metaphlan_v4.1.1",
    "usagePath": "parameters/metaphlan_v4.1.1_usage.json",
    "paraPath": "parameters/metaphlan_v4.1.1_para.json",
    "html": "tool.ejs",
    "selectionRoute": "/complete-selection-metaphlan_v4.1.1",
    "env": "",
    "hasStderr": true
  },
  "metaspades_v4.2.0": {
    "title": "metaspades_v4.2.0 Parameters",
    "toolName": "metaspades_v4.2.0",
    "route": "metaspades_v4.2.0",
    "commandRoute": "/run-command-metaspades_v4.2.0",
    "usagePath": "parameters/metaspades_v4.2.0_usage.json",
    "paraPath": "parameters/metaspades_v4.2.0_para.json",
    "html": "tool.ejs",
    "selectionRoute": "/complete-selection-metaspades_v4.2.0",
    "env": "",
    "hasStderr": true
  },
  "pyani_v0.2.12": {
    "title": "pyani_v0.2.12 Parameters",
    "toolName": "pyani_v0.2.12",
    "route": "pyani_v0.2.12",
    "commandRoute": "/run-command-pyani_v0.2.12",
    "usagePath": "parameters/pyani_v0.2.12_usage.json",
    "paraPath": "parameters/pyani_v0.2.12_para.json",
    "html": "tool.ejs",
    "selectionRoute": "/complete-selection-pyani_v0.2.12",
    "env": "",
    "hasStderr": true
  }
};